"""Summary report generation for OH MCD workflow."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime

import pandas as pd

from project.vendors.vendor_scanner import VendorFileResult

LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class SummaryReport:
    batch_date: str
    transmission_count: int
    encounter_count: int
    total_paid_amount: float
    worksheet_name: str
    vendor_lines: list[str]
    anomaly_detected: bool
    anomaly_message: str | None


class ReportGenerator:
    """Create summarized metrics and human-readable email body text."""

    def __init__(self, anomaly_threshold_pct: float) -> None:
        self.anomaly_threshold_pct = anomaly_threshold_pct

    def _build_vendor_lines(self, vendor_results: list[VendorFileResult]) -> list[str]:
        lines: list[str] = []
        for result in vendor_results:
            if result.found:
                lines.append(f"- {result.vendor}: {result.file_name} ({result.modified_time})")
            else:
                lines.append(f"- {result.vendor}: MISSING")
        return lines

    def build_summary(
        self,
        dataframe: pd.DataFrame,
        worksheet_name: str,
        vendor_results: list[VendorFileResult],
        previous_encounter_total: int | None,
    ) -> SummaryReport:
        """Generate summary metrics and anomaly flags."""
        transmission_count = int(dataframe["transmissionfilename"].nunique()) if not dataframe.empty else 0
        encounter_count = int(dataframe["Number"].fillna(0).sum()) if "Number" in dataframe.columns else 0
        total_paid_amount = float(dataframe["TotalPaidAmount"].fillna(0).sum()) if "TotalPaidAmount" in dataframe.columns else 0.0

        anomaly_detected = False
        anomaly_message = None
        if previous_encounter_total and previous_encounter_total > 0:
            delta_pct = abs(encounter_count - previous_encounter_total) / previous_encounter_total * 100
            if delta_pct >= self.anomaly_threshold_pct:
                anomaly_detected = True
                anomaly_message = (
                    f"Encounter count anomaly detected. Current={encounter_count}, "
                    f"Previous={previous_encounter_total}, Delta={delta_pct:.1f}%"
                )
                LOGGER.warning(anomaly_message)

        return SummaryReport(
            batch_date=datetime.now().strftime("%Y-%m-%d"),
            transmission_count=transmission_count,
            encounter_count=encounter_count,
            total_paid_amount=total_paid_amount,
            worksheet_name=worksheet_name,
            vendor_lines=self._build_vendor_lines(vendor_results),
            anomaly_detected=anomaly_detected,
            anomaly_message=anomaly_message,
        )

    @staticmethod
    def render_email_body(summary: SummaryReport) -> str:
        """Build plain text email body for business users."""
        lines = [
            "OH MCD Submission Automation Report",
            "",
            f"Batch Date: {summary.batch_date}",
            f"Worksheet: {summary.worksheet_name}",
            f"Number of transmission files: {summary.transmission_count}",
            f"Encounter counts: {summary.encounter_count}",
            f"Total paid amount: ${summary.total_paid_amount:,.2f}",
            "",
            "Vendor attestation files:",
            *summary.vendor_lines,
        ]

        if summary.anomaly_detected and summary.anomaly_message:
            lines.extend(["", f"ALERT: {summary.anomaly_message}"])

        lines.append("\nGenerated by OH MCD Submission Counts Automation.")
        return "\n".join(lines)
